const nav=document.querySelector('.navbar');
const onScroll=()=>nav.classList.toggle('scrolled',window.scrollY>40);window.addEventListener('scroll',onScroll,{passive:true});onScroll();
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in-view')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const pillarObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.65});document.querySelectorAll('.pillars span').forEach(el=>pillarObserver.observe(el));
const links=[...document.querySelectorAll('nav a')];const sections=links.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean);const sectionObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){links.forEach(l=>l.classList.toggle('active',l.getAttribute('href')==='#'+e.target.id))}}),{rootMargin:'-35% 0px -55% 0px',threshold:0});sections.forEach(s=>sectionObserver.observe(s));
const mobile=document.querySelector('.mobile-menu');const menu=document.querySelector('.menu');const closeMenu=document.querySelector('.close-menu');function toggleMenu(open){mobile.classList.toggle('open',open);mobile.setAttribute('aria-hidden',String(!open));menu.setAttribute('aria-expanded',String(open));document.body.classList.toggle('lock',open)}menu.addEventListener('click',()=>toggleMenu(true));closeMenu.addEventListener('click',()=>toggleMenu(false));mobile.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>toggleMenu(false)));
const overlay=document.querySelector('#overlay');const overlayContent=document.querySelector('#overlayContent');const closeOverlay=()=>{overlay.classList.remove('open');overlay.setAttribute('aria-hidden','true');document.body.classList.remove('lock')};document.querySelector('.overlay-close').addEventListener('click',closeOverlay);overlay.addEventListener('click',e=>{if(e.target===overlay)closeOverlay()});
const loreHtml=`<span class="micro">BOYZ / LORE</span><h2>THE LORE<br><em>before the reputation.</em></h2><div class="chapter"><h3>THE BEGINNING</h3><p>Por muito tempo, disseram aos homens como deveriam ser. Fortes, discretos, masculinos, mas nunca vaidosos demais. Até que alguns decidiram que não precisavam escolher entre personalidade e respeito.</p></div><div class="chapter"><h3>THE FIRST BOYZ</h3><p>O primeiro boy não era uma pessoa específica. Era uma atitude: entrar em qualquer lugar sem pedir licença para ser exatamente quem se é.</p></div><div class="chapter"><h3>WHY BOYZ?</h3><p>BOYZ nasceu para representar uma geração de homens que transformou aparência, presença e personalidade em assinatura. Bonitos, ambiciosos, extravagantes, competitivos e impossíveis de ignorar.</p></div><div class="chapter"><h3>THE STANDARD</h3><p>Não existe um molde. Existe um padrão de presença. Cada boy deve ter algo próprio — um estilo, um talento, uma energia, uma história — que faça as pessoas lembrarem dele.</p></div><p class="micro">PRETTY. POPULAR. PROBLEMATIC.</p>`;
const rulesHtml=`<span class="micro">THE RULES / THE CODE IN PRACTICE</span><h2>THE<br><em>RULES.</em></h2>${[['RESPECT THE CIRCLE','Respeite seus irmãos. Você pode discordar, competir e provocar. Mas nunca destrua quem está ao seu lado.'],['BE YOURSELF','Não existe uma maneira correta de ser um boy. Sua liberdade termina onde começa a liberdade de outro.'],['LOOK GOOD','Cuide da aparência. Tenha estilo. Esteja apresentável. A cidade está olhando — e você sabe disso.'],['COMPETE','Quer ser o mais bonito, estiloso, talentoso ou influente? Vá atrás. Seu irmão é seu rival na competição, não seu inimigo.'],['DON’T BE BORING','Participe. Apareça. Provoque. Crie histórias. Um boy não nasceu para ficar no canto.'],['KNOW YOUR PLACE','Hierarquia organiza responsabilidade, não valor. Respeite quem lidera e quem está começando.'],['NEVER HUMILIATE YOUR OWN','Brincadeira faz parte. Humilhação não. Saiba a diferença.'],['REPRESENT BOYZ','Você pode ser caótico, provocador ou dramático. Saiba quando está falando por você e quando está carregando o nome BOYZ.'],['WHAT STAYS HERE...','Histórias, conversas e confidências merecem discrição. Confiança se conquista.'],['KNOW WHEN TO STOP','Competição não é crueldade. Liberdade não é licença para prejudicar os outros.']].map(([h,p])=>`<div class="chapter"><h3>${h}</h3><p>${p}</p></div>`).join('')}<div class="chapter"><h3>THE GOLDEN RULE</h3><p><strong>“Isso torna os BOYZ mais fortes ou mais fracos?”</strong></p></div>`;
const profiles={joe:{name:'JOE HILLS',role:'ALPHA / FOUNDER',quote:'“Não preciso ser o maior para ocupar espaço. Preciso ser impossível de ignorar.”',about:'Fundador dos BOYZ e parte da liderança que transformou uma atitude em uma fraternidade construída sobre presença, ambição e excelência.',known:'Visão, presença e ambição.',signature:'O homem que não pede licença para ocupar espaço.'},loy:{name:'LOY HILLS',role:'ALPHA / FOUNDER',quote:'“Se existe um lugar no topo, alguém precisa ter coragem para chegar até ele.”',about:'Fundador dos BOYZ e parte da liderança que sustenta a visão, a estética e a ambição da fraternidade.',known:'Liderança, coragem e direção.',signature:'Transformar ambição em movimento.'}};
function profileHtml(p){return `<div class="profile-full"><div class="mini-portrait"><span>${p.name.split(' ')[0]}</span></div><div><span class="micro">${p.role}</span><h2>${p.name}</h2><blockquote>${p.quote}</blockquote><div class="chapter"><h3>ABOUT</h3><p>${p.about}</p></div><div class="chapter"><h3>KNOWN FOR</h3><p>${p.known}</p></div><div class="chapter"><h3>SIGNATURE</h3><p>${p.signature}</p></div></div></div>`}
function openOverlay(html){overlayContent.innerHTML=html;overlay.classList.add('open');overlay.setAttribute('aria-hidden','false');document.body.classList.add('lock');overlay.querySelector('h2')?.focus()};document.querySelectorAll('[data-panel="rules"]').forEach(b=>b.addEventListener('click',()=>openOverlay(rulesHtml)));document.querySelector('a[href="#lore-page"]')?.addEventListener('click',e=>{e.preventDefault();openOverlay(loreHtml)});document.querySelectorAll('[data-profile]').forEach(b=>b.addEventListener('click',()=>openOverlay(profileHtml(profiles[b.dataset.profile]))));
window.addEventListener('keydown',e=>{if(e.key==='Escape'){if(mobile.classList.contains('open'))toggleMenu(false);if(overlay.classList.contains('open'))closeOverlay();}});
