const nav=document.querySelector('.navbar');
const onScroll=()=>nav.classList.toggle('scrolled',window.scrollY>40);window.addEventListener('scroll',onScroll,{passive:true});onScroll();
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in-view')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const pillarObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.65});document.querySelectorAll('.pillars span').forEach(el=>pillarObserver.observe(el));
const links=[...document.querySelectorAll('nav a')];const sections=links.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean);const sectionObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){links.forEach(l=>l.classList.toggle('active',l.getAttribute('href')==='#'+e.target.id))}}),{rootMargin:'-35% 0px -55% 0px',threshold:0});sections.forEach(s=>sectionObserver.observe(s));
const mobile=document.querySelector('.mobile-menu');const menu=document.querySelector('.menu');const closeMenu=document.querySelector('.close-menu');function toggleMenu(open){mobile.classList.toggle('open',open);mobile.setAttribute('aria-hidden',String(!open));menu.setAttribute('aria-expanded',String(open));document.body.classList.toggle('lock',open)}menu.addEventListener('click',()=>toggleMenu(true));closeMenu.addEventListener('click',()=>toggleMenu(false));mobile.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>toggleMenu(false)));
const overlay=document.querySelector('#overlay');const overlayContent=document.querySelector('#overlayContent');const closeOverlay=()=>{overlay.classList.remove('open');overlay.setAttribute('aria-hidden','true');document.body.classList.remove('lock')};document.querySelector('.overlay-close').addEventListener('click',closeOverlay);overlay.addEventListener('click',e=>{if(e.target===overlay)closeOverlay()});
const loreHtml=`<span class="micro">BEASTS / LORE</span><h2>THE LORE<br><em>before the name.</em></h2><div class="chapter"><h3>THE BEGINNING</h3><p>Por muito tempo, disseram aos homens como deveriam ser. Fortes, mas nunca delicados. Confiantes, mas nunca vaidosos. Competitivos, mas nunca extravagantes. Até que alguns decidiram que não precisavam escolher.</p></div><div class="chapter"><h3>THE FIRST BEAST</h3><p>Ele não tinha um nome. Porque nunca foi sobre uma única pessoa. Era sobre um homem que decidiu parar de pedir permissão para ser quem era. Quando perguntaram por quê, sua resposta foi simples: “Porque posso.”</p></div><div class="chapter"><h3>WHY BEASTS?</h3><p>“Beast” começou como um rótulo para homens considerados indomáveis, excessivos ou difíceis de controlar. Eles transformaram o rótulo em identidade. Ser Beast significa não permitir que outra pessoa determine o limite daquilo que você pode ser.</p></div><div class="chapter"><h3>THE TOP</h3><p>Liberdade nunca significou acomodação. O topo não pertence a ninguém. Ele é conquistado. E quando um Beast chega lá, outro já está vindo atrás.</p></div><p class="micro">THERE IS ALWAYS A BEAST AT THE TOP.</p>`;
const rulesHtml=`<span class="micro">THE RULES / THE CODE IN PRACTICE</span><h2>THE<br><em>RULES.</em></h2>${[['RESPECT THE DEN','Respeite seus irmãos. Você pode discordar, competir e provocar. Mas nunca destrua quem está ao seu lado.'],['BE YOURSELF','Não existe uma maneira correta de ser um Beast. Sua liberdade termina onde começa a liberdade de outro.'],['LOOK GOOD','Cuide da aparência. Tenha estilo. Seja apresentável. A cidade está olhando.'],['COMPETE','Quer ser o mais bonito, estiloso, talentoso ou influente? Go for it. Seu irmão é seu rival na competição, não seu inimigo.'],['DON’T BE BORING','Participe. Apareça. Provoque. Crie histórias. Um Beast não foi feito para ficar sentado no canto.'],['KNOW YOUR PLACE','Hierarquia existe para organizar responsabilidade, não para definir valor.'],['NEVER HUMILIATE YOUR OWN','Brincadeira faz parte. Humilhação não. Saiba a diferença.'],['REPRESENT BEASTS','Você pode ser caótico, provocador ou dramático. Só saiba quando está carregando o nome BEASTS.'],['WHAT HAPPENS IN THE DEN...','Histórias, conversas e confidências merecem discrição. Trust is earned.'],['KNOW WHEN TO STOP','Competição não é crueldade. Liberdade não é licença para prejudicar os outros.']].map(([h,p])=>`<div class="chapter"><h3>${h}</h3><p>${p}</p></div>`).join('')}<div class="chapter"><h3>THE GOLDEN RULE</h3><p><strong>“Isso torna os BEASTS mais fortes ou mais fracos?”</strong></p></div>`;
const profiles={joe:{name:'JOE HILLS',role:'ALPHA / FOUNDER',quote:'“Não preciso ser o maior para ocupar espaço. Preciso ser impossível de ignorar.”',about:'Fundador dos BEASTS e parte da liderança que transforma a ideia de liberdade e excelência em presença real na cidade.',known:'Visão, presença e ambição.',signature:'O homem que não pede licença para ocupar espaço.'},loy:{name:'LOY HILLS',role:'ALPHA / FOUNDER',quote:'“Se existe um lugar no topo, alguém precisa ter coragem para chegar até ele.”',about:'Fundador dos BEASTS e parte da liderança que sustenta a visão, a identidade e a ambição da fraternidade.',known:'Liderança, coragem e direção.',signature:'Transformar ambição em movimento.'}};
function profileHtml(p){return `<div class="profile-full"><div class="mini-portrait"><span>${p.name.split(' ')[0]}</span></div><div><span class="micro">${p.role}</span><h2>${p.name}</h2><blockquote>${p.quote}</blockquote><div class="chapter"><h3>ABOUT</h3><p>${p.about}</p></div><div class="chapter"><h3>KNOWN FOR</h3><p>${p.known}</p></div><div class="chapter"><h3>SIGNATURE</h3><p>${p.signature}</p></div></div></div>`}
function openOverlay(html){overlayContent.innerHTML=html;overlay.classList.add('open');overlay.setAttribute('aria-hidden','false');document.body.classList.add('lock');overlay.querySelector('h2')?.focus()};document.querySelectorAll('[data-panel="rules"]').forEach(b=>b.addEventListener('click',()=>openOverlay(rulesHtml)));document.querySelector('a[href="#lore-page"]')?.addEventListener('click',e=>{e.preventDefault();openOverlay(loreHtml)});document.querySelectorAll('[data-profile]').forEach(b=>b.addEventListener('click',()=>openOverlay(profileHtml(profiles[b.dataset.profile]))));
window.addEventListener('keydown',e=>{if(e.key==='Escape'){if(mobile.classList.contains('open'))toggleMenu(false);if(overlay.classList.contains('open'))closeOverlay();}});
